### ISSUE TITLE
GPU requirement?

### ISSUE THREAD

**Issue by ganav** [jhfjhfj1/autokeras#22]
Thank you for sharing your project sir. 

I am about to use this source for my journal paper.
Original papers said that the authers used several hundreds of graphic card to run AutoML.

How about this source? 
Ex: in my case, i am using only one Titan X graphic card with 5000 images (224x224x3).
Actually i already got memory error. What is minimum requirement of graphic card to run this source sir?

**Comment by DharamDK** [comment]
Not sure about the Memory requirement of AutoML but this Memory error depends on your dataset size as well.
Since you are using a few thousand RGB images, it will take up a huge space and eventually may fail on VRAM/RAM in execution.
And "Batch size" is not yet configurable from the user side, so you will not be even able to trim down data flowing per batch.
I suggest to try with just a few hundred images and monitor the Memory used up!

**Comment by jhfjhfj1** [comment]
Thank you for the question.
Currently, we do not support loading batch by batch.
We may implement it later.

If really in need, you can submit an issue with the feature request template for it.
Thanks.
