### ISSUE TITLE
No module named 'autokeras.text'

### ISSUE THREAD

**Issue by ronykroy** [jhfjhfj1/autokeras#283]
### Reproducing Steps
  * Step 1: set up a fresh conda environment [python v > 3.6]
  * Step 2: install torch version as specified in req.txt, followed by torch vision
  * Step 3: install : pip install autokeras
  * Step 4: down load the text.py and the .tsv file int he same folder at github path mentioned above

### Setup Details
Include the details about the versions of:
 - OS type and version: windows 8
 - Python: 3.6.6
 - autokeras: 0.2.18
 - scikit-learn: 0.19.1
 - numpy: 1.15.3
 - keras: 2.2.2
 - scipy: 1.1.0
 - tensorflow: 1.11.0
 - pytorch:

**Comment by mlaradji** [comment]
Hi @ronykroy,

I believe the problem occurs because the `text` module, along with the `nn` or `image` modules, don't get installed with `pip install autokeras`, which is my case as well. As a temporary solution, you can clone the repository and either use autokeras from there, or copy the submodules you need to your Python's autokeras ($PYTHON_DIR/lib/python3.6/site-packages/autokeras).

As for why the submodules don't get installed, my (unexpert) intuition is that there's something wrong with the `setup.py` file. Perhaps the submodules need to be explicitly declared there?

**Comment by jhfjhfj1** [comment]
This issue is fixed with the latest version.
Please refer tot he tutorial.
https://autokeras.com/start/#automated-text-classifier-tutorial
