### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by hiteshn97** [jhfjhfj1/autokeras#34]
I am trying the example mnist.py but repeatedly getting this error. I have uninstalled tensorflow and reinstalled it's latest version but the problem still persists. How can I rectify this? P.S. all solutions I found online were for Windows, I am using Ubuntu 18.04

**Comment by Jangol** [comment]
Hi， 
You can try uninstalling the tensoflow library and reinstalling it.

**Comment by hiteshn97** [comment]
Tried. Uninstalled protobuf, tf and reinstalled them. Still same error.

**Comment by hiteshn97** [comment]
tf : 1.9.0
protobuf : 3.6.0

**Comment by Jangol** [comment]
You can try the lower version of tf，and after uninstalled the tf remove the residual folder in the python site-packages.
My version：
Keras：2.1.5
tf：1.6.0

**Comment by rodrigob** [comment]
Same problem. Uninstalling & reinstalling did not help :(

**Comment by owen-t** [comment]
Hey @rodrigob I just had the same problem. I fixed it by:

1. Uninstalling everything from pip.
2. Deleting all my site-packages directories (found by doing python -m site)
3. Reinstalling using pip with the --no-cache-dir option. Reinstalling without the --no-cache-dir didn't resolve the problem.

Step (2) is probably not needed due to step (1), but I haven't checked that.

HTH,

Owen.
