### ISSUE TITLE
There is a murmur by voice_generation , can it support voice to text or speech recognition

### ISSUE THREAD

**Issue by wjnodejs** [jhfjhfj1/autokeras#462]
There is a murmur by voice_generation , can it support voice to text or speech recognition

**Comment by boyuangong** [comment]
Hi there, thanks for your interests to our package! We are currently working on the voice to text model. The voice generation model is only for text to voice(.wav file).

**Comment by boyuangong** [comment]
Please refer to #448

**Comment by boyuangong** [comment]
Please specify your environment and your script so that we can repeat. Also, we cannot make sure that every text can be converted to 100% accurate and clear. That's the limitation of the current model [deep voice  3](https://arxiv.org/pdf/1710.07654.pdf). Please feel free to let me know if you have any questions.

**Comment by wjnodejs** [comment]
linux cpu:2 memory:2g 
python file:![image](https://user-images.githubusercontent.com/6300447/51310594-f67cfb00-1a81-11e9-9747-4acce76d42dc.png)
voice file:[test_0 (2).zip](https://github.com/jhfjhfj1/autokeras/files/2768083/test_0.2.zip)
