### ISSUE TITLE
Do you support rnn structure?

### ISSUE THREAD

**Issue by touching-foots-huskie** [jhfjhfj1/autokeras#7]
I am working on rnn predicting by keras. And I want to know if this autokeras can support it?

**Comment by jhfjhfj1** [comment]
@touching-foots-huskie Currently not, but we might start to implement RNN after the image classifier is ready.

**Comment by KPreal** [comment]
On the same topic,
What types of ML problems are supported? There are only examples of image classification tasks.
In my specific case, I'm interested in multi-target regression with continuous and categorical inputs. Does Auto-Keras handle categorical variables for example with support for embeddings?

**Comment by xuzhang5788** [comment]
You only support the image classification problems. Am I right? If my problem is similar to the image classification, but my input images are 3D instead of 2D. Can I still use your AutoKeras to figure out the better architectures and hyperparameters for 3D convolutional neural networks? Thanks for sharing your library.

**Comment by jhfjhfj1** [comment]
We currently do not support tabular data for now.
Currently, we only support Image classification.
But more functions will be added soon.

Thank you for the question.

**Comment by h44632186** [comment]
Hi, Does auto keras support regression problem? Does it suppoert LSTM network?
Thx.
